Stretching
JannisX11/blockbench pull request #1806
Opened 2023-04-03 21:47 UTC by AaronWoodward

This PR adds a stretching tool (for generic models only) which acts like inflate, but is multiplicative and can be done on each access individually (or on all of them in unison). It can also be disabled in the settings.

As suggested, I went through all mentions of `inflate` and updated accordingly to account for stretching.

The only instance I wasn't sure how to handle is `validator.js` line 170. @JannisX11 
I also wasn't sure what the files in the second commit are about - so I separated them for easy removal if they aren't meant to be merged.

https://user-images.githubusercontent.com/20425809/229634036-cdffc1e6-be5d-4755-bf89-66ff0c408099.mp4

2023-04-04 20:55 UTC, JannisX11 requested changes
Here's my review. A couple changes are needed to integrate this.

The integration of stretch in validator.js L170 would be something like this:
```javascript
let invalid_size_axes = size.filter((value, axis) => value < 0.999 && (value+cube.inflate*2) * cube.stretch[axis] > 0.005);
```

2023-04-04 20:55 UTC, JannisX11 commented on js/interface/actions.js
> +			condition: () => settings.stretch_enabled.value && Format.id === "free",
Let's use a format feature flag to condition the stretch feature.
The flag can be defined here https://github.com/JannisX11/blockbench/blob/master/js/io/format.js#L241 like the others and can be accessed via:
`Format.stretch_cubes`
or
`{features: ['stretch_cubes']}`
The flag can be enabled when defining a format. This way we can re-use this if we ever create a dedicated format, or other people want to use this feature in their formats.

2023-04-04 20:55 UTC, JannisX11 commented on js/modeling/transform.js
> +		condition: function() {return Cube.selected.length && Modes.edit},
The sliders and link toggle should also be conditioned on the feature flag. Yeah, the toolbar gets disabled, but users would still be able to add these to other toolbars and they wouldn't work correctly.

2023-04-04 20:55 UTC, JannisX11 commented on js/modeling/transform.js
> +			modes: ['edit', 'animate'],
The toggle should ideally have the same conditions as the sliders. So enabled only when cubes are enabled, not any type of element. And only enabled in edit mode, not in animate mode.

2023-04-04 20:55 UTC, JannisX11 commented on service_worker.js
No need to include these auto-generated files like package-lock and service_worker in the PR. I only build them before each update.

2023-04-04 20:55 UTC, JannisX11 commented on js/outliner/cube.js
> +		from[i] = (from[i] - element.inflate) * element.stretch[i];
Multiplying the absolute coordinates of the cube currently not only stretches the cube, but also moves it's position away from the scene origin. The stretch should be calculated from the local center of the cube (the middle value between from and to).

2023-04-05 00:01 UTC, AaronWoodward commented
@JannisX11 Thanks for the great feedback! I believe I have addressed it all.

2023-04-25 07:00 UTC, merged