Added tool and gizmo for stretching
JannisX11/blockbench pull request #2213
Opened 2024-02-27 19:16 UTC by AaronWoodward

This PR extends the transform gizmo functionality to support modifying a cube's stretch values. A corresponding tool was also added (default shortcut of `alt + s` to match scale which is just `s`). Probably not the best icon for it but I didn't see a better one in font awesome's collection.

2024-03-01 22:17 UTC, JannisX11 requested changes
A few notes, but otherwise this is working well and can be merged.

2024-03-01 22:17 UTC, JannisX11 commented on js/interface/actions.js
> +			new Tool('stretch_tool', {
We should set a condition on this tool to only make it available in formats with the stretch_cubes feature.

2024-03-01 22:17 UTC, JannisX11 commented on js/modeling/transform_gizmo.js
> +						if ((event.shiftKey || Pressing.overrides.shift) && (channel === 'scale' || channel === 'stretch')) {
This part is only for display mode, so stretch tool integration isn't necessary

2024-03-01 22:17 UTC, JannisX11 commented on js/webpack/bundle.js
This file is now in gitignore and no longer tracked on Git, so it should be removed

2024-03-01 22:17 UTC, JannisX11 commented on js/modeling/transform_gizmo.js
> +					} else if (Toolbox.selected.transformerMode === 'scale' || Toolbox.selected.transformerMode === 'stretch') {
This part is only for display mode, so stretch tool integration isn't necessary

2024-03-01 22:17 UTC, JannisX11 commented on js/modeling/transform_gizmo.js
> +					} else if (Toolbox.selected.id == 'resize_tool' || Toolbox.selected.id === 'stretch_tool' || (Toolbox.selected.id === 'rotate_tool' && BarItems.rotation_space.value !== 'global')) {
This part is only for animation mode, so stretch tool integration isn't necessary

2024-03-01 22:17 UTC, JannisX11 commented on js/modeling/transform_gizmo.js
>  							})
Would be good to have a different edit message here (2 lines down). "Resize" and "Stretch".

2024-03-05 21:04 UTC, aaron-warden commented on js/interface/actions.js
> +			new Tool('stretch_tool', {
Good call!

2024-03-05 21:29 UTC, AaronWoodward commented on js/interface/actions.js
> +			new Tool('stretch_tool', {
Good call!

2024-03-05 21:33 UTC, AaronWoodward commented
> A few notes, but otherwise this is working well and can be merged.

Thanks for the feedback @JannisX11! Fixed that all up :)

2024-03-09 21:15 UTC, merged